export const patients = [
  // Nurse 1 – 6 patients
  {
    id: 1,
    nurseId: 1,
    name: "Sara Mohamed",
    age: 68,
    gender: "Female",
    diagnosis: "Post-surgery recovery",
    condition: "Severe back pain (8/10)",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP slightly elevated",
    medications: "Pain killers twice daily",
    carePlan: "Daily visit + exercises",
    image:
      "https://live-production.wcms.abc-cdn.net.au/7948e290b30a29ce23cc60ddf8a842ea?impolicy=wcms_crop_resize&cropH=670&cropW=1005&xPos=0&yPos=52&width=862&height=575",
  },
  {
    id: 2,
    nurseId: 1,
    name: "Ahmed Ali",
    age: 55,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Blood sugar stable",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Normal glucose level",
    medications: "Insulin",
    carePlan: "Weekly follow-up",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/005/346/410/small/close-up-portrait-of-smiling-handsome-young-caucasian-man-face-looking-at-camera-on-isolated-light-gray-studio-background-photo.jpg",
  },
  {
    id: 3,
    nurseId: 1,
    name: "Nour Hassan",
    age: 72,
    gender: "Female",
    diagnosis: "Heart failure follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "Low BP reported",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://inews.co.uk/wp-content/uploads/2019/02/Mariam-Khan-2-c-FACEphotography-Read-Only-e1550495818625.jpg?w=800&h=644&crop=1",
  },
  {
    id: 4,
    nurseId: 1,
    name: "Omar Khaled",
    age: 60,
    gender: "Male",
    diagnosis: "Hypertension",
    condition: "BP controlled",
    acuity: "Stable",
    lastVisit: "Today",
    vitalNotes: "BP 120/80",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeRzppZdUGys7tYOW7RkSqvVeQlloZg-dii-wJHJrtL3CmNoLf8cwj0hNHY9TjIkoh5SY&usqp=CAU",
  },
  {
    id: 5,
    nurseId: 1,
    name: "Laila Samir",
    age: 48,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://img.freepik.com/premium-photo/islam-muslim-woman-hijab-with-islamic-clothes-traditional-religion-arabic-culture-spiritual-faith-portrait-senior-beauty-skincare-happy-iraq-face-smile-cosmetics-makeup_590464-105134.jpg",
  },
  {
    id: 6,
    nurseId: 1,
    name: "Hassan Mostafa",
    age: 50,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 saturation 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFMv3xXUWQ_UymielHwEcjmvimnByuE_ohtw&s",
  },

  // Nurse 2 – 6 patients
  {
    id: 7,
    nurseId: 2,
    name: "Mona Salah",
    age: 63,
    gender: "Female",
    diagnosis: "Arthritis management",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Swelling noted",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://media.istockphoto.com/id/1180178844/photo/wearing-my-hijab-and-glowing-with-pride.jpg?s=612x612&w=0&k=20&c=jC4f6qB5EP302BZP6Gsbsub5DZg8s-Adr9r2qrvX1_U=",
  },
  {
    id: 8,
    nurseId: 2,
    name: "Karim Fathy",
    age: 57,
    gender: "Male",
    diagnosis: "Kidney check-up",
    condition: "Stable",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Normal lab results",
    medications: "None",
    carePlan: "Monthly monitoring",
    image:
      "https://us.images.westend61.de/0000752461j/indian-man-in-office-portrait-WESTF21808.jpg",
  },
  {
    id: 9,
    nurseId: 2,
    name: "Huda Youssef",
    age: 70,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://plus.unsplash.com/premium_photo-1679064458881-76904cf6d1aa?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aGlqYWJ8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 10,
    nurseId: 2,
    name: "Tamer Adel",
    age: 65,
    gender: "Male",
    diagnosis: "Lung recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 saturation 94%",
    medications: "Inhalers",
    carePlan: "Visit every 2 days",
    image:
      "https://thumbs.dreamstime.com/b/serious-handsome-young-indian-professional-man-looking-camera-formal-suit-confident-stylish-businessman-executive-legal-315449484.jpg",
  },
  {
    id: 11,
    nurseId: 2,
    name: "Fatma Nabil",
    age: 53,
    gender: "Female",
    diagnosis: "Diabetes check-up",
    condition: "Blood sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Sugar 150 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://img.freepik.com/premium-photo/portrait-confident-muslim-business-woman-hijab-with-modern-building-background_606562-1001.jpg",
  },
  {
    id: 12,
    nurseId: 2,
    name: "Mohamed Samir",
    age: 61,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "Pain level 6/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://thumbs.dreamstime.com/b/young-indian-man-happy-outdoors-looking-camera-39595562.jpg",
  },

  // Nurse 3 – 6 patients
  {
    id: 13,
    nurseId: 3,
    name: "Amira Hassan",
    age: 58,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://images.stockcake.com/public/a/4/f/a4f7b055-78e5-489f-aa79-85e4a0145f3e_large/professional-hijab-wearing-woman-stockcake.jpg",
  },
  {
    id: 14,
    nurseId: 3,
    name: "Sami Mahmoud",
    age: 66,
    gender: "Male",
    diagnosis: "Kidney stones",
    condition: "Pain mild",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Creatinine normal",
    medications: "Pain killers",
    carePlan: "Weekly monitoring",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDjj4FYuHLSMiO_VLOQZ_Vkaya2jWw86WQCQ&s",
  },
  {
    id: 15,
    nurseId: 3,
    name: "Lina Farid",
    age: 62,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://deenspiration.com/wp-content/uploads/2018/01/muslim-woman-wearing-hijab.jpg",
  },
  {
    id: 16,
    nurseId: 3,
    name: "Youssef Adel",
    age: 59,
    gender: "Male",
    diagnosis: "Diabetes",
    condition: "Sugar controlled",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Sugar 120 mg/dL",
    medications: "Insulin",
    carePlan: "Weekly follow-up",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvSj61_acbo0rLzb5gapolOiqqkpaqKi9OCl6nyDXWP-ebYz36G1GiQklYls7hNiCJDTA&usqp=CAU",
  },
  {
    id: 17,
    nurseId: 3,
    name: "Dina Samir",
    age: 55,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain mild",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image: "https://images.pexels.com/photos/8575867/pexels-photo-8575867.jpeg",
  },
  {
    id: 18,
    nurseId: 3,
    name: "Khaled Fathi",
    age: 64,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://images.unsplash.com/photo-1615109398623-88346a601842?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFufGVufDB8fDB8fHww",
  },

  // Nurse 4 – 6 patients
  {
    id: 19,
    nurseId: 4,
    name: "Maha Nabil",
    age: 67,
    gender: "Female",
    diagnosis: "Post-surgery recovery",
    condition: "Pain moderate",
    acuity: "High",
    lastVisit: "Yesterday",
    vitalNotes: "BP slightly elevated",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://media.istockphoto.com/id/1183434777/photo/welcome-face.jpg?s=612x612&w=0&k=20&c=lXW3i28UmRJ4DAJwoi9JPxYUEQd3Hf-fwSS2fnIMhMc=",
  },
  {
    id: 20,
    nurseId: 4,
    name: "Adel Youssef",
    age: 60,
    gender: "Male",
    diagnosis: "Hypertension",
    condition: "BP stable",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "BP 125/80",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://www.shutterstock.com/image-photo/happy-handsome-young-african-american-600nw-2432719071.jpg",
  },
  {
    id: 21,
    nurseId: 4,
    name: "Rania Salah",
    age: 59,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://i.pinimg.com/474x/a9/ca/e8/a9cae86f6bd5181f62d70c0df9b5df62.jpg",
  },
  {
    id: 22,
    nurseId: 4,
    name: "Amr Khaled",
    age: 56,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_343g81-dqyq2ztU-t18Reb5cMPrN7j3qSokhhlFr1XdlVk-1BZTek3N4Gy0yuVbm-YA&usqp=CAU",
  },
  {
    id: 23,
    nurseId: 4,
    name: "Nadia Farid",
    age: 61,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://i.pinimg.com/564x/f6/5f/c7/f65fc715b6002c5892f644b3a3d6032f.jpg",
  },
  {
    id: 24,
    nurseId: 4,
    name: "Othman Sami",
    age: 65,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://img.freepik.com/free-photo/young-bearded-man-with-denim-shirt_273609-7230.jpg?semt=ais_hybrid&w=740&q=80",
  },

  // Nurse 5 – 6 patients
  {
    id: 25,
    nurseId: 5,
    name: "Salma Nabil",
    age: 68,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image: "https://images.pexels.com/photos/9218726/pexels-photo-9218726.jpeg",
  },
  {
    id: 26,
    nurseId: 5,
    name: "Fady Adel",
    age: 59,
    gender: "Male",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://img.freepik.com/free-photo/young-bearded-man-with-denim-shirt_273609-7230.jpg?semt=ais_hybrid&w=740&q=80",
  },
  {
    id: 27,
    nurseId: 5,
    name: "Mariam Samir",
    age: 60,
    gender: "Female",
    diagnosis: "Diabetes",
    condition: "Sugar controlled",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Sugar 120 mg/dL",
    medications: "Insulin",
    carePlan: "Weekly follow-up",
    image:
      "https://img.freepik.com/free-photo/beautiful-woman-wearing-hijab_23-2149288966.jpg?semt=ais_hybrid&w=740&q=80",
  },
  {
    id: 28,
    nurseId: 5,
    name: "Hany Khaled",
    age: 63,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "Pain level 5/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?cs=srgb&dl=pexels-italo-melo-881954-2379004.jpg&fm=jpg",
  },
  {
    id: 29,
    nurseId: 5,
    name: "Aya Hassan",
    age: 57,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://i.pinimg.com/736x/7c/7f/cb/7c7fcb47e65fec252042d36326030554.jpg",
  },
  {
    id: 30,
    nurseId: 5,
    name: "Mohamed Fathy",
    age: 62,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://as2.ftcdn.net/jpg/01/15/48/31/1000_F_115483122_xg8vzNZn5ATABQHtPLlMXMU7ePsukI2X.jpg",
  },

  // Nurse 6 – 6 patients
  {
    id: 31,
    nurseId: 6,
    name: "Noha Adel",
    age: 66,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://i.pinimg.com/736x/d8/06/33/d80633d096d9fe52c00513d69694b1ea.jpg",
  },
  {
    id: 32,
    nurseId: 6,
    name: "Omar Samir",
    age: 55,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://as1.ftcdn.net/v2/jpg/07/71/30/78/500_F_771307811_iR66rILi6ejV0qhf4fPC5OoGi0qgZyZn.jpg",
  },
  {
    id: 33,
    nurseId: 6,
    name: "Farah Youssef",
    age: 68,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsQkHmBG0m2nNkpmodIlw-996r3fwNePDBVupPorfp9OKlSmoacH4mUYbBlt6uAu97Gu8&usqp=CAU",
  },
  {
    id: 34,
    nurseId: 6,
    name: "Hossam Khaled",
    age: 61,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://as2.ftcdn.net/jpg/02/32/80/57/1000_F_232805769_mY3gAqlZ28O5PPE5w7YqQg5RiFEJToI6.jpg",
  },
  {
    id: 35,
    nurseId: 6,
    name: "Salma Farid",
    age: 64,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://img.freepik.com/premium-photo/portrait-beautiful-young-woman-hijab-against-blurred-background_1048944-14756280.jpg",
  },
  {
    id: 36,
    nurseId: 6,
    name: "Faris Adel",
    age: 59,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "Pain level 6/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://thumbs.dreamstime.com/b/indian-man-portrait-close-up-happy-young-56800239.jpg",
  },

  // Nurse 7 – 6 patients
  {
    id: 37,
    nurseId: 7,
    name: "Mona Nabil",
    age: 62,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjEeZ2LSzcaMQQolWoSlDOaonvLxBxCpFgTmsCSzBB5CjeTYinwDC4o2R6ZFolkj8ooC4&usqp=CAU",
  },
  {
    id: 38,
    nurseId: 7,
    name: "Khalid Fathy",
    age: 67,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://media.assettype.com/thequint%2F2016-04%2Fb7e5ca6f-6a68-479a-bf85-2fe72f814efe%2FiStock_000079450013_Large.jpg?rect=0%2C0%2C2721%2C1531&auto=format%2Ccompress&fmt=webp&width=720&w=1200",
  },
  {
    id: 39,
    nurseId: 7,
    name: "Huda Adel",
    age: 65,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://images.pexels.com/photos/9218726/pexels-photo-9218726.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 40,
    nurseId: 7,
    name: "Sami Samir",
    age: 58,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://us.images.westend61.de/0000752461j/indian-man-in-office-portrait-WESTF21808.jpg",
  },
  {
    id: 41,
    nurseId: 7,
    name: "Dina Nabil",
    age: 61,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "2 days ago",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image: "https://images.pexels.com/photos/9218626/pexels-photo-9218626.jpeg",
  },
  {
    id: 42,
    nurseId: 7,
    name: "Omar Fathy",
    age: 63,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://media.istockphoto.com/id/649754084/photo/smiling-man.jpg?s=170667a&w=0&k=20&c=V70QxOgArZ_23eFLsYpD3w8SUuHb8NkgCiyTH7icnqs=",
  },

  // Nurse 8 – 6 patients
  {
    id: 43,
    nurseId: 8,
    name: "Leila Samir",
    age: 59,
    gender: "Female",
    diagnosis: "Diabetes",
    condition: "Sugar controlled",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Sugar 120 mg/dL",
    medications: "Insulin",
    carePlan: "Weekly follow-up",
    image:
      "https://png.pngtree.com/png-clipart/20250602/original/pngtree-beautiful-woman-wearing-a-hijab-png-image_21115486.png",
  },
  {
    id: 44,
    nurseId: 8,
    name: "Hany Fathy",
    age: 65,
    gender: "Male",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Yesterday",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://media.istockphoto.com/id/613557584/photo/portrait-of-a-beautifull-smiling-man.jpg?s=612x612&w=0&k=20&c=hkCg5CrmTKOApePbPOyo1U9GexEfIJOJqoLXJIvcN8E=",
  },
  {
    id: 45,
    nurseId: 8,
    name: "Sara Farid",
    age: 60,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT26YF-ZZamnXrH4Wu-6qXCA589LN2Xm4RrhNX4XuWPXcFBIWoH7a-w7jPmAuT4gDdnpGI&usqp=CAU",
  },
  {
    id: 46,
    nurseId: 8,
    name: "Tamer Nabil",
    age: 58,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "Pain level 6/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://media.istockphoto.com/id/522189227/photo/hes-got-the-look.jpg?s=612x612&w=0&k=20&c=lUFeE0YLONQlH1u1gJSpYt5PHM0edUPh5m2mCdWBsHg=",
  },
  {
    id: 47,
    nurseId: 8,
    name: "Mona Farid",
    age: 61,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://images.pexels.com/photos/539727/pexels-photo-539727.jpeg?cs=srgb&dl=pexels-danangwicaksono-539727.jpg&fm=jpg",
  },
  {
    id: 48,
    nurseId: 8,
    name: "Faris Khaled",
    age: 64,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://media.istockphoto.com/id/531862866/photo/im-proud-of-all-my-achievements.jpg?s=612x612&w=0&k=20&c=PnGmt5YPb1ycwRRYiPItFEysvmjAnviKV1nHGSPy1ds=",
  },

  // Nurse 9 – 6 patients
  {
    id: 49,
    nurseId: 9,
    name: "Aya Samir",
    age: 66,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://t3.ftcdn.net/jpg/06/27/53/68/360_F_627536897_QzFBXE4YkFN13KjNF1F2c5PfRb2sxkep.jpg",
  },
  {
    id: 50,
    nurseId: 9,
    name: "Mohamed Adel",
    age: 59,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTakrQnVXQLQQ0OIF5H0k9zxJiup2TGflq696wt0tNdV2UmTzy_ghNLccC7vK_DOy-1PQo&usqp=CAU",
  },
  {
    id: 51,
    nurseId: 9,
    name: "Leila Fathy",
    age: 62,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Yesterday",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://thumbs.dreamstime.com/b/portrait-hijab-wearing-traditional-muslim-woman-arabic-style-studio-headshot-proud-cultural-arab-beautiful-skin-250345571.jpg",
  },
  {
    id: 52,
    nurseId: 9,
    name: "Omar Nabil",
    age: 63,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/005/346/410/small/close-up-portrait-of-smiling-handsome-young-caucasian-man-face-looking-at-camera-on-isolated-light-gray-studio-background-photo.jpg",
  },
  {
    id: 53,
    nurseId: 9,
    name: "Salma Hassan",
    age: 64,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://img.freepik.com/free-photo/front-view-woman-wearing-halal-outdoors_23-2150701516.jpg?semt=ais_hybrid&w=740&q=80",
  },
  {
    id: 54,
    nurseId: 9,
    name: "Faris Samir",
    age: 59,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "Yesterday",
    vitalNotes: "Pain level 6/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://media.istockphoto.com/id/613557584/photo/portrait-of-a-beautifull-smiling-man.jpg?s=612x612&w=0&k=20&c=hkCg5CrmTKOApePbPOyo1U9GexEfIJOJqoLXJIvcN8E=",
  },

  // Nurse 10 – 6 patients
  {
    id: 55,
    nurseId: 10,
    name: "Huda Farid",
    age: 61,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://www.shutterstock.com/image-photo/close-muslim-woman-portrait-smiling-600nw-2253605821.jpg",
  },
  {
    id: 56,
    nurseId: 10,
    name: "Tamer Khaled",
    age: 58,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://t3.ftcdn.net/jpg/02/00/90/24/360_F_200902415_G4eZ9Ok3Ypd4SZZKjc8nqJyFVp1eOD6V.jpg",
  },
  {
    id: 57,
    nurseId: 10,
    name: "Dina Samir",
    age: 60,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://png.pngtree.com/thumb_back/fw800/background/20220915/pngtree-smiling-arab-woman-in-hijab-at-home-business-face-headscarf-photo-image_48621886.jpg",
  },
  {
    id: 58,
    nurseId: 10,
    name: "Mohamed Farid",
    age: 63,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/070/171/972/small/relaxed-man-meditating-modern-interior-setting-photo.jpg",
  },
  {
    id: 59,
    nurseId: 10,
    name: "Mona Adel",
    age: 65,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://www.shutterstock.com/image-photo/closeup-portrait-cheerful-muslim-lady-260nw-1906980403.jpg",
  },
  {
    id: 60,
    nurseId: 10,
    name: "Hany Samir",
    age: 61,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://media.istockphoto.com/id/1323167284/photo/young-successful-indian-man-wearing-stylish-eyeglasses-standing-on-the-street-handsome-asian.jpg?s=170667a&w=0&k=20&c=RmFpHJBfMvjBxwnHhrns8Ba02HIeL70l1LA9Wl23II4=",
  },

  // Nurse 11 – 6 patients
  {
    id: 61,
    nurseId: 11,
    name: "Salma Nabil",
    age: 64,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://media.istockphoto.com/id/1194745993/photo/smiling-muslim-woman-wearing-hijab.jpg?s=612x612&w=0&k=20&c=8yu_OxGaAiDQas7hjLBy8-CnjY40r5Gxw06dZV8lxFs=",
  },
  {
    id: 62,
    nurseId: 11,
    name: "Faris Khaled",
    age: 66,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "Yesterday",
    vitalNotes: "Pain level 5/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://media.istockphoto.com/id/1323167284/photo/young-successful-indian-man-wearing-stylish-eyeglasses-standing-on-the-street-handsome-asian.jpg?s=170667a&w=0&k=20&c=RmFpHJBfMvjBxwnHhrns8Ba02HIeL70l1LA9Wl23II4=",
  },
  {
    id: 63,
    nurseId: 11,
    name: "Leila Samir",
    age: 63,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://www.shutterstock.com/image-photo/closeup-photo-portrait-young-beautiful-600nw-2301240243.jpg",
  },
  {
    id: 64,
    nurseId: 11,
    name: "Omar Khaled",
    age: 59,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoxMUc_2D0YRzfmsaVQb5aE3pfTFXRowyngA&s",
  },
  {
    id: 65,
    nurseId: 11,
    name: "Mona Farid",
    age: 60,
    gender: "Female",
    diagnosis: "Hypertension",
    condition: "BP slightly high",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "BP 140/90",
    medications: "ACE inhibitors",
    carePlan: "Monthly monitoring",
    image:
      "https://media.istockphoto.com/id/1430323239/photo/young-muslim-woman-using-smartphone-indoors.jpg?s=612x612&w=0&k=20&c=v70j9OD3XnghZrJO_jpnfPMv6KxD3ZgPnMAwRSfVm2w=",
  },
  {
    id: 66,
    nurseId: 11,
    name: "Hany Adel",
    age: 62,
    gender: "Male",
    diagnosis: "Diabetes check-up",
    condition: "Sugar slightly high",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Sugar 145 mg/dL",
    medications: "Metformin",
    carePlan: "Weekly follow-up",
    image:
      "https://img.freepik.com/free-photo/portrait-handsome-smiling-stylish-hipster-lambersexual-model-sexy-man-dressed-tshirt-jeans-fashion-male-isolated-blue-wall-studio_158538-26731.jpg?semt=ais_hybrid&w=740&q=80",
  },

  // Nurse 12 – 6 patients
  {
    id: 67,
    nurseId: 12,
    name: "Aya Nabil",
    age: 61,
    gender: "Female",
    diagnosis: "Heart disease follow-up",
    condition: "Low energy",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "BP fluctuating",
    medications: "Beta blockers",
    carePlan: "Strict monitoring",
    image:
      "https://img.freepik.com/premium-photo/portrait-successful-happy-businesswoman-hijab-office-worker-smiling-looking-camera_321831-13841.jpg",
  },
  {
    id: 68,
    nurseId: 12,
    name: "Tamer Fathy",
    age: 63,
    gender: "Male",
    diagnosis: "Lung infection recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "O2 96%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://img.freepik.com/free-photo/portrait-white-man-isolated_53876-40306.jpg?semt=ais_hybrid&w=740&q=80",
  },
  {
    id: 69,
    nurseId: 12,
    name: "Dina Farid",
    age: 65,
    gender: "Female",
    diagnosis: "Arthritis",
    condition: "Joint pain moderate",
    acuity: "Moderate",
    lastVisit: "2 days ago",
    vitalNotes: "Swelling mild",
    medications: "Anti-inflammatory",
    carePlan: "Daily exercises",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkn13MsRrW5O9IMtyGkFsyhHWeEjsxOJFQo2HDD2uBaH3d-Gkr7OkbFc9nEq9eeA36tFs&usqp=CAU",
  },
  {
    id: 70,
    nurseId: 12,
    name: "Mohamed Samir",
    age: 60,
    gender: "Male",
    diagnosis: "Post-surgery recovery",
    condition: "Pain controlled",
    acuity: "High",
    lastVisit: "Today",
    vitalNotes: "Pain level 6/10",
    medications: "Pain killers",
    carePlan: "Daily monitoring",
    image:
      "https://img.freepik.com/free-photo/handsome-cheerful-man-with-happy-smile_176420-18028.jpg?semt=ais_hybrid&w=740&q=80",
  },
  {
    id: 71,
    nurseId: 12,
    name: "Mona Hassan",
    age: 62,
    gender: "Female",
    diagnosis: "Fracture recovery",
    condition: "Mobility improving",
    acuity: "Moderate",
    lastVisit: "Yesterday",
    vitalNotes: "Mild swelling",
    medications: "Pain relief",
    carePlan: "Physio exercises",
    image:
      "https://media.istockphoto.com/id/1179968207/photo/cheerful-malaysian-businesswoman-in-a-cafe.jpg?s=612x612&w=0&k=20&c=zzC0F72bFhxMiMy1Nb9Z8zlVp_FK3CANgkb4XCOoEU8=",
  },
  {
    id: 72,
    nurseId: 12,
    name: "Faris Fathy",
    age: 64,
    gender: "Male",
    diagnosis: "Pneumonia recovery",
    condition: "Breathing improving",
    acuity: "Moderate",
    lastVisit: "Today",
    vitalNotes: "O2 95%",
    medications: "Antibiotics",
    carePlan: "Visit every 2 days",
    image:
      "https://img.freepik.com/free-photo/close-up-portrait-handsome-smiling-young-man-white-t-shirt-blurry-outdoor-nature_176420-6305.jpg?semt=ais_hybrid&w=740&q=80",
  },
];
