export const nursesData = [
  {
    id:1,
    name: "Nurse Sara",
    imageUrl: "https://img.freepik.com/premium-photo/arabic-female-nurse-with-hijab-working-hospital_952161-131473.jpg",
    specialty: "Home Injection",
    rating: "4.7",
    distance: "Cairo",
    gender: "Female",
  },
  {
    id:2,
    name: "Nurse Omar",
    imageUrl: "https://media.istockphoto.com/id/1783744987/photo/medical-arms-crossed-doctor-with-portrait-of-man-for-healthcare-surgery-and-happy-smile.jpg?s=612x612&w=0&k=20&c=AHHdkbG8P4il6oxSdl6qm00pg4aBJBCWjs0QVMti_F4=",
    specialty: "Blood Pressure & Sugar Measurement",
    rating: "4.9",
    distance: "Alexandria",
    gender: "Male",
  },
  {
    id:3,
    name: "Nurse Hania",
    imageUrl: "https://img.freepik.com/premium-photo/portrait-young-muslim-woman-doctor-standing-hall-hospital-dressed-hijab_1145931-46540.jpg",
    specialty: "Postnatal Care",
    rating: "4.8",
    distance: "Giza",
    gender: "Female",
  },
  {
    id:4,
    name: "Nurse Yara",
    imageUrl: "https://thumbs.dreamstime.com/b/portrait-friendly-muslim-doctor-nurse-wearing-hijab-medical-face-mask-gloves-gray-background-195201052.jpg",
    specialty: "Elderly Care",
    rating: "4.6",
    distance: "Mansoura",
    gender: "Female",
  },
  {
    id:5,
    name: "Nurse Ali",
    imageUrl: "https://media.istockphoto.com/id/1186255987/photo/male-nurse-with-stethoscope-standing-at-clinic-he-is-smiling-and-looking-at-the-camera.jpg?s=612x612&w=0&k=20&c=M6B_hIl0x5sfJ_ODc9m2E1ZGlfJap4cLDHvT6SY3IwM=",
    specialty: "Wound Dressing",
    rating: "4.5",
    distance: "Tanta",
    gender: "Male",
  },
  {
    id:6,
    name: "Nurse Laila",
    imageUrl: "https://static.vecteezy.com/system/resources/thumbnails/028/139/476/small/muslim-nurse-hijab-generate-ai-photo.jpg",
    specialty: "Blood Pressure & Temperature Measurement",
    rating: "4.8",
    distance: "Aswan",
    gender: "Female",
  },
  {
    id:7,
    name: "Nurse Omar H.",
    imageUrl: "https://us.images.westend61.de/0001035624pw/portrait-of-smiling-young-male-nurse-in-blue-scrubs-standing-with-arms-crossed-against-wall-at-hospital-MASF09216.jpg",
    specialty: "Blood Pressure & Sugar Measurement",
    rating: "4.9",
    distance: "Cairo",
    gender: "Male",
  },
  {
    id:8,
    name: "Nurse Dina",
    imageUrl: "https://img.freepik.com/premium-photo/islamic-female-nurse-with-hidjab-wearing-blue_1198745-356.jpg",
    specialty: "Postnatal Care",
    rating: "4.7",
    distance: "Alexandria",
    gender: "Female",
  },
  {
    id:9,
    name: "Nurse Karim",
    imageUrl: "https://www.eurekahomehealthcare.com/wp-content/uploads/2024/08/healthcare-workers-medicine-covid-19-pandemic-self-quarantine-concept-cheerful-smiling-hispanic-male-nurse-doctor-er-wearing-scrubs-glasses-talking-patient-clinic-scaled.jpg",
    specialty: "Home Injection",
    rating: "4.6",
    distance: "Giza",
    gender: "Male",
  },
  {
    id:10,
    name: "Nurse Huda",
    imageUrl: "https://thumbs.dreamstime.com/b/muslim-doctor-nurse-woman-hijab-stethoscope-white-coat-shows-her-hand-to-space-text-blue-portrait-194509292.jpg",
    specialty: "Wound Dressing",
    rating: "4.8",
    distance: "Mansoura",
    gender: "Female",
  },
  {
    id:11,
    name: "Nurse Sami",
    imageUrl: "https://thumbs.dreamstime.com/b/young-doctor-holding-file-standing-front-his-team-396399313.jpg",
    specialty: "Elderly Care",
    rating: "4.7",
    distance: "Tanta",
    gender: "Male",
  },
  {
    id:12,
    name: "Nurse Reem",
    imageUrl: "https://img.freepik.com/premium-photo/portrait-muslim-female-doctor-with-stethoscope-white-coat-holding-medical-document_368093-6542.jpg?semt=ais_hybrid&w=740&q=80",
    specialty: "Postnatal Care",
    rating: "4.9",
    distance: "Aswan",
    gender: "Female",
  },
];

export default nursesData;
