export const nursesData = [
  {
    id: 1,
    name: "الممرضة سارة",
    nameEn: "Nurse Sara",
    imageUrl:
      "https://img.freepik.com/premium-photo/arabic-female-nurse-with-hijab-working-hospital_952161-131473.jpg",
    specialty: "Home Injection",
    specialtyAr: "حقن منزلية",
    rating: "4.7",
    distance: "Cairo",
    distanceAr: "القاهرة",
    gender: "Female",
    patients: [1, 2, 3, 4, 5, 6],
    appointments: [
      {
        id: 1,
        name: "mohamed sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "09:00 AM",
        patientId: 1,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 2,
        name: "ahmed mohamed",
        phone: "(+20) 133-436-7890",
        date: "2025-11-27",
        time: "11:00 AM",
        patientId: 2,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 3,
        name: "ahmed sami",
        phone: "(+20) 123-457-7891",
        date: "2025-11-27",
        time: "02:00 PM",
        patientId: 3,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 4,
        name: "mohamed ali",
        phone: "(+20) 127-457-7890",
        date: "2025-11-28",
        time: "08:30 AM",
        patientId: 4,
        task: "Blood Sugar Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 5,
        name: "Ali elsayed",
        phone: "(+20) 129-456-7890",
        date: "2025-11-28",
        time: "10:00 AM",
        patientId: 5,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 6,
        name: "khaled ahmed",
        phone: "(+20) 123-406-7890",
        date: "2025-11-28",
        time: "01:00 PM",
        patientId: 6,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 2,
      tasksComplete: 2,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },
  {
    id: 2,
    name: "الممرض عمر",
    nameEn: "Nurse Omar",
    imageUrl:
      "https://media.istockphoto.com/id/1783744987/photo/medical-arms-crossed-doctor-with-portrait-of-man-for-healthcare-surgery-and-happy-smile.jpg?s=612x612&w=0&k=20&c=AHHdkbG8P4il6oxSdl6qm00pg4aBJBCWjs0QVMti_F4=",
    specialty: "Blood Pressure & Sugar Measurement",
    specialtyAr: "قياس ضغط الدم والسكر",
    rating: "4.9",
    distance: "Alexandria",
    distanceAr: "الإسكندرية",
    gender: "Male",
    patients: [7, 8, 9, 10, 11, 12],
    appointments: [
      {
        id: 7,
        name: "sami mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "09:30 AM",
        patientId: 7,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 8,
        name: "adel hamada",
        phone: "(+20) 123-456-7999",
        date: "2025-11-27",
        time: "11:30 AM",
        patientId: 8,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 9,
        name: "mohamed adel",
        phone: "(+20) 123-488-7890",
        date: "2025-11-27",
        time: "02:30 PM",
        patientId: 9,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 10,
        name: "ahmed adel",
        phone: "(+20) 123-556-7890",
        date: "2025-11-28",
        time: "09:00 AM",
        patientId: 10,
        task: "Blood Sugar Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 11,
        name: "shimaa samy",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "10:30 AM",
        patientId: 11,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 12,
        name: "mohamed magdii",
        phone: "(+20) 123-666-7890",
        date: "2025-11-28",
        time: "01:30 PM",
        patientId: 12,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 2,
      tasksComplete: 2,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },
  {
    id: 3,
    name: "الممرضة هانية",
    nameEn: "Nurse Hania",
    imageUrl:
      "https://img.freepik.com/premium-photo/portrait-young-muslim-woman-doctor-standing-hall-hospital-dressed-hijab_1145931-46540.jpg",
    specialty: "Postnatal Care",
    specialtyAr: "رعاية ما بعد الولادة",
    rating: "4.8",
    distance: "Giza",
    distanceAr: "الجيزة",
    gender: "Female",
    patients: [13, 14, 15, 16, 17, 18],
    appointments: [
      {
        id: 13,
        name: "ashraqat ahmed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 13,
        task: "Therapy Review",
        type: "Therapy",
        status: "Upcoming",
      },
      {
        id: 14,
        name: "mohamed ali",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "10:30 AM",
        patientId: 14,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 15,
        name: "sami ali",
        phone: "(+20) 123-456-7870",
        date: "2025-11-29",
        time: "12:00 PM",
        patientId: 15,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 16,
        name: "nahed mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "09:30 AM",
        patientId: 16,
        task: "Blood Sugar Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 17,
        name: "menna mohamed",
        phone: "(+20) 123-455-7890",
        date: "2025-11-30",
        time: "11:00 AM",
        patientId: 17,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 18,
        name: "mohamed sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "01:00 PM",
        patientId: 18,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 1,
      tasksComplete: 2,
      activeTreatment: 1,
      pendingTasks: 2,
    },
  },
  {
    id: 4,
    name: "الممرضة يارا",
    nameEn: "Nurse Yara",
    imageUrl:
      "https://thumbs.dreamstime.com/b/portrait-friendly-muslim-doctor-nurse-wearing-hijab-medical-face-mask-gloves-gray-background-195201052.jpg",
    specialty: "Elderly Care",
    specialtyAr: "رعاية المسنين",
    rating: "4.6",
    distance: "Mansoura",
    distanceAr: "المنصورة",
    gender: "Female",
    patients: [19, 20, 21, 22, 23, 24],
    appointments: [
      {
        id: 19,
        name: "ahmed rabiea",
        phone: "(+20) 123-456-7999",
        date: "2025-11-27",
        time: "09:00 AM",
        patientId: 19,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 20,
        name: "ibrahim ahmed",
        phone: "(+20) 122-456-7890",
        date: "2025-11-27",
        time: "11:00 AM",
        patientId: 20,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 21,
        name: "mahmoud mohamed",
        phone: "(+20) 123-456-7880",
        date: "2025-11-28",
        time: "09:30 AM",
        patientId: 21,
        task: "Blood Sugar Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 22,
        name: "omar mahmoud",
        phone: "(+20) 123-456-8890",
        date: "2025-11-28",
        time: "10:30 AM",
        patientId: 22,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 23,
        name: "osama ahmed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 23,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 24,
        name: "khaled mostafa",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "11:00 AM",
        patientId: 24,
        task: "Therapy Review",
        type: "Therapy",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 2,
      tasksComplete: 20,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },

  {
    id: 5,
    name: "الممرض علي",
    nameEn: "Nurse Ali",
    imageUrl:
      "https://media.istockphoto.com/id/1186255987/photo/male-nurse-with-stethoscope-standing-at-clinic-he-is-smiling-and-looking-at-the-camera.jpg?s=612x612&w=0&k=20&c=M6B_hIl0x5sfJ_ODc9m2E1ZGlfJap4cLDHvT6SY3IwM=",
    specialty: "Wound Dressing",
    specialtyAr: "تضميد الجروح",
    rating: "4.5",
    distance: "Tanta",
    distanceAr: "طنطا",
    gender: "Male",
    patients: [25, 26, 27, 28, 29, 30],
    appointments: [
      {
        id: 25,
        name: "Aly Ibrahim",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "09:00 AM",
        patientId: 25,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 26,
        name: "mohamed Aly",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "10:30 AM",
        patientId: 26,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 27,
        name: "mohaned aly",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "12:00 PM",
        patientId: 27,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 28,
        name: "doaa elsayed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "09:00 AM",
        patientId: 28,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 29,
        name: "fatma mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "10:30 AM",
        patientId: 29,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 30,
        name: "hana sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "01:00 PM",
        patientId: 30,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 2,
      tasksComplete: 26,
      activeTreatment: 2,
      pendingTasks: 1,
    },
  },
  {
    id: 6,
    name: "الممرضة ليلى",
    nameEn: "Nurse Laila",
    imageUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/028/139/476/small/muslim-nurse-hijab-generate-ai-photo.jpg",
    specialty: "Blood Pressure & Temperature Measurement",
    specialtyAr: "قياس ضغط الدم ودرجة الحرارة",
    rating: "4.8",
    distance: "Aswan",
    distanceAr: "أسوان",
    gender: "Female",
    patients: [31, 32, 33, 34, 35, 36],
    appointments: [
      {
        id: 31,
        name: "hagar ashraf",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 31,
        task: "Vitals Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 32,
        name: "habiba mohsen",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "10:30 AM",
        patientId: 32,
        task: "Blood Pressure Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 33,
        name: "alaa hassan",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "12:00 PM",
        patientId: 33,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 34,
        name: "arwa mahmoud",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "09:30 AM",
        patientId: 34,
        task: "Temperature Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 35,
        name: "amira sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "11:00 AM",
        patientId: 35,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 36,
        name: "esraa ashraf",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "01:00 PM",
        patientId: 36,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 3,
      tasksComplete: 29,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },

  {
    id: 8,
    name: "الممرضة دينا",
    nameEn: "Nurse Dina",
    imageUrl:
      "https://img.freepik.com/premium-photo/islamic-female-nurse-with-hidjab-wearing-blue_1198745-356.jpg",
    specialty: "Postnatal Care",
    specialtyAr: "رعاية ما بعد الولادة",
    rating: "4.7",
    distance: "Alexandria",
    distanceAr: "الإسكندرية",
    gender: "Female",
    patients: [43, 44, 45, 46, 47, 48],
    appointments: [
      {
        id: 43,
        name: "Ibrahim sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 43,
        task: "Therapy Review",
        type: "Therapy",
        status: "Upcoming",
      },
      {
        id: 44,
        name: "mohamed shreif",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "10:30 AM",
        patientId: 44,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 45,
        name: "Adel Ashraf",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "12:00 PM",
        patientId: 45,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 46,
        name: "mohamed Abdelrahman",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "09:30 AM",
        patientId: 46,
        task: "Blood Pressure Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 47,
        name: "mohmoud sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "11:00 AM",
        patientId: 47,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 48,
        name: "khaled sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "01:00 PM",
        patientId: 48,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 9,
      tasksComplete: 8,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },
  {
    id: 9,
    name: "الممرض كريم",
    nameEn: "Nurse Karim",
    imageUrl:
      "https://www.eurekahomehealthcare.com/wp-content/uploads/2024/08/healthcare-workers-medicine-covid-19-pandemic-self-quarantine-concept-cheerful-smiling-hispanic-male-nurse-doctor-er-wearing-scrubs-glasses-talking-patient-clinic-scaled.jpg",
    specialty: "Home Injection",
    specialtyAr: "حقن منزلية",
    rating: "4.6",
    distance: "Giza",
    distanceAr: "الجيزة",
    gender: "Male",
    patients: [49, 50, 51, 52, 53, 54],
    appointments: [
      {
        id: 49,
        name: "kareem sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "09:00 AM",
        patientId: 49,
        task: "Injection",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 50,
        name: "mohamed ashraf",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "10:30 AM",
        patientId: 50,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 51,
        name: "ashraf sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "12:00 PM",
        patientId: 51,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 52,
        name: "mohamed Abdullah",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "09:30 AM",
        patientId: 52,
        task: "Injection",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 53,
        name: "Arabi sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "11:00 AM",
        patientId: 53,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 54,
        name: "mohamed sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "01:00 PM",
        patientId: 54,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 7,
      tasksComplete: 10,
      activeTreatment: 2,
      pendingTasks: 3,
    },
  },
  {
    id: 10,
    name: "الممرضة هدى",
    nameEn: "Nurse Huda",
    imageUrl:
      "https://thumbs.dreamstime.com/b/muslim-doctor-nurse-woman-hijab-stethoscope-white-coat-shows-her-hand-to-space-text-blue-portrait-194509292.jpg",
    specialty: "Wound Dressing",
    specialtyAr: "تضميد الجروح",
    rating: "4.8",
    distance: "Mansoura",
    distanceAr: "المنصورة",
    gender: "Female",
    patients: [55, 56, 57, 58, 59, 60],
    appointments: [
      {
        id: 55,
        name: "shimaa ahmed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 55,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 56,
        name: "Abdelhamid Mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "10:30 AM",
        patientId: 56,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 57,
        name: "Youmna sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "12:00 PM",
        patientId: 57,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 58,
        name: "Yara sami",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "09:30 AM",
        patientId: 58,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 59,
        name: "Yahia Mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "11:00 AM",
        patientId: 59,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 60,
        name: "zakaria khaled",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "01:00 PM",
        patientId: 60,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 3,
      tasksComplete: 50,
      activeTreatment: 1,
      pendingTasks: 2,
    },
  },
  {
    id: 11,
    name: "الممرض سامي",
    nameEn: "Nurse Sami",
    imageUrl:
      "https://thumbs.dreamstime.com/b/young-doctor-holding-file-standing-front-his-team-396399313.jpg",
    specialty: "Elderly Care",
    specialtyAr: "رعاية المسنين",
    rating: "4.7",
    distance: "Tanta",
    distanceAr: "طنطا",
    gender: "Male",
    patients: [61, 62, 63, 64, 65, 66],
    appointments: [
      {
        id: 61,
        name: "Mohamed Behery",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "09:00 AM",
        patientId: 61,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 62,
        name: "Mohamed Salah",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "10:30 AM",
        patientId: 62,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 63,
        name: "Mohamed Mostafa",
        phone: "(+20) 123-456-7890",
        date: "2025-11-27",
        time: "12:00 PM",
        patientId: 63,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
      {
        id: 64,
        name: "Asmaa Abdelhamead",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "09:30 AM",
        patientId: 64,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 65,
        name: "Abdullah Aly",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "11:00 AM",
        patientId: 65,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 66,
        name: "Araby Mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-28",
        time: "01:00 PM",
        patientId: 66,
        task: "Dressing Change",
        type: "Procedure",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 5,
      tasksComplete: 30,
      activeTreatment: 3,
      pendingTasks: 2,
    },
  },
  {
    id: 12,
    name: "الممرضة ريم",
    nameEn: "Nurse Reem",
    imageUrl:
      "https://img.freepik.com/premium-photo/portrait-muslim-female-doctor-with-stethoscope-white-coat-holding-medical-document_368093-6542.jpg?semt=ais_hybrid&w=740&q=80",
    specialty: "Postnatal Care",
    specialtyAr: "رعاية ما بعد الولادة",
    rating: "4.9",
    distance: "Aswan",
    distanceAr: "أسوان",
    gender: "Female",
    patients: [67, 68, 69, 70, 71, 72],
    appointments: [
      {
        id: 67,
        name: "Ahmed Mostafa",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "09:00 AM",
        patientId: 67,
        task: "Therapy Review",
        type: "Therapy",
        status: "Upcoming",
      },
      {
        id: 68,
        name: "tarek ahmed",
        phone: "(+20) 123-456-7888",
        date: "2025-11-29",
        time: "10:30 AM",
        patientId: 68,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 69,
        name: "moamen mohamed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-29",
        time: "12:00 PM",
        patientId: 69,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
      {
        id: 70,
        name: "menna aly",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "09:30 AM",
        patientId: 70,
        task: "Blood Sugar Check",
        type: "Checkup",
        status: "Upcoming",
      },
      {
        id: 71,
        name: "nada ahmed",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "11:00 AM",
        patientId: 71,
        task: "Vitals Check",
        type: "Checkup",
        status: "Completed",
      },
      {
        id: 72,
        name: "ahmed ibrahim",
        phone: "(+20) 123-456-7890",
        date: "2025-11-30",
        time: "01:00 PM",
        patientId: 72,
        task: "Medication Admin",
        type: "Medication",
        status: "Upcoming",
      },
    ],
    dashboardStats: {
      todayAppointments: 7,
      tasksComplete: 22,
      activeTreatment: 2,
      pendingTasks: 2,
    },
  },
];

export default nursesData;
